services:
  - type: web
    name: aclick-baixador-motor
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
